---
- hosts: all
  sudo:  true
  vars:
    doc_root: /var/www/web
    legacy_doc_root: /var/www/innomatic_legacy/innomatic 
    sys_packages:
      - mcrypt
    php_packages:
      - { name: dev, package: php5.6-dev }
      - { name: pear, package: php-pear }
      - { name: xdebug, package: php5.6-xdebug }
      - { name: curl, package: php5.6-curl }
      - { name: mcrypt, package: php5.6-mcrypt }
      - { name: mysql, package: php5.6-mysql }
      - { name: redis, package: php5.6-redis }
      - { name: apc, package: php-apc }
      - { name: zip, package: php5.6-zip }
      - { name: dom, package: php5.6-dom }
    php_ppa: php
  roles:
    - init
    - nginx
    - php5-fpm
    - php5-cli
    - php5-common
    - composer
    - mysql
    - git
    - curl
    - sqlite
    - wget
